import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ali Hasan Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add favicon links */}
        <link rel="icon" href="/ali.png" sizes="any" type="image/x-icon" />
        <link rel="icon" href="/ali.png" type="image/jpeg" />
        <link rel="apple-touch-icon" href="/ali.jpg" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
